# Generated by Django 6.0.4 on 2026-05-04 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='importado',
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=100),
        ),
    ]
